### ISSUE TITLE
Users Chat & Questions

### ISSUE THREAD

**Issue by MoSal** [saldl/saldl#4]
This is a meta bug for users questions.

If you have a question. Ask it here.

**Comment by noctuid** [comment]
How does this compare to aria2c? What would you say are the major differences?

**Comment by MoSal** [comment]
@noctuid
I will try to write a wiki page about this.

**Comment by professorjamesmoriarty** [comment]
I understand "Chunk Progress States" makes use of 0-4 to display its state. Is there any method or plans to allow you to change the numbers used with other chars?

**Comment by MoSal** [comment]
@shaggytwodope
Hello.
I just pushed a couple of commits that make it easy to change those chars at compile-time to any ASCII chars you like.
https://github.com/saldl/saldl/blob/master/src/progress.h#L26

**Comment by professorjamesmoriarty** [comment]
@MoSal That's awesome, thank you.

**Comment by bitwave** [comment]
is it possible to download with 4 connections, and 1mb chunks, but in random order?

**Comment by MoSal** [comment]
@bitwave 
I think I can add logic to download chunks in random order. But I'm interested in knowing
the rationale behind that request first.

What is exactly the use-case?

**Comment by bitwave** [comment]
just for completeness for aria2 vs saldl. I'm using multiple download tools, to check my firewall and server performance with downloading large files.

**Comment by MoSal** [comment]
@bitwave 
Just pushed b9373336dc78906a173468ad067c31c34e57a9a9 which implements `--random-order`.

**Comment by akramkun** [comment]
i have an error:
The configuration failed
(complete log in /home/mypc/Downloads/apps/saldl-40/build/config.log)

**Comment by akramkun** [comment]
i had this erroe:
`Waf: Leaving directory `/home/mypc/Downloads/apps/saldl-40/build'
Build failed
Traceback (most recent call last):
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Task.py", line 156, in process
    ret=self.run()
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Build.py", line 548, in run
    fun(x.abspath(),y.abspath(),x.path_from(launch_node))
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Build.py", line 584, in do_install
    raise Errors.WafError('Could not install the file %r'%tgt,e)
WafError: Could not install the file '/usr/bin/saldl'

Traceback (most recent call last):
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Task.py", line 156, in process
    ret=self.run()
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Build.py", line 548, in run
    fun(x.abspath(),y.abspath(),x.path_from(launch_node))
  File "/home/mypc/Downloads/apps/saldl-40/.waf-2.0.8-206f2b7a89029e71942a2beb9e1bbbbd/waflib/Build.py", line 584, in do_install
    raise Errors.WafError('Could not install the file %r'%tgt,e)
WafError: Could not install the file '/usr/share/man/man1/saldl.1'`

**Comment by rlaphoenix** [comment]
1. How do you compile this on windows?
2. Will you ever continue releasing pre-built Windows executables? Perhaps even installers using something like Inno Setup Compiler?
